name: Run Job Alerts

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 5:00 AM IST (23:30 UTC)
  workflow_dispatch:

jobs:
  job-alerts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run job alerts
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: python main.py
